#local docker-compose.yaml for netops-mcp-chat application
services:
  sequential-thinking-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netops-sequential-thinking-mcp
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file: .env
    environment:
      - SEQUENTIAL_MCP_URL=http://sequential-thinking-mcp:8003/mcp
  